"""
    appendix_lambda_grouping_tables.jl

Read the aggregate Lambda output from `appendix_lambda_table.jl` and write
publication-ready LaTeX tables for the three main paper scenarios. Each table
contains only the aggregate separation ratio Lambda, with rows for candidate
set size `m` and columns for grouping variables.

Run with:

    julia +1.11.9 --startup-file=no --project=PrefPol \
        PrefPol/running/appendix_lambda_grouping_tables.jl
"""

using CSV
using DataFrames
using Printf
using PrefPol
import PrefPol as pp

const INPUT_DIR = joinpath(
    pp.project_root,
    "running",
    "output",
    "all_scenarios_small",
    "appendix_lambda_table",
)
const INPUT_CSV = joinpath(INPUT_DIR, "appendix_lambda_table.csv")
const OUTPUT_TEX = joinpath(INPUT_DIR, "appendix_lambda_grouping_tables.tex")

const TARGET_SPECS = [
    (year = 2006, scenario = "main_2006"),
    (year = 2018, scenario = "main_2018"),
    (year = 2022, scenario = "main_2022"),
]

const GROUPING_ORDER = Dict(
    (2006, "main_2006") => ["Age", "Education", "Ideology", "Income", "PT", "Sex"],
    (2018, "main_2018") => ["Age", "Education", "Ideology", "Income", "LulaScoreGroup", "Race", "Religion", "Sex"],
    (2022, "main_2022") => ["Abortion", "Age", "Education", "Ideology", "Income", "PT", "Race", "Religion", "Sex"],
)

function latex_escape(value)
    return replace(
        string(value),
        "\\" => "\\textbackslash{}",
        "_" => "\\_",
        "%" => "\\%",
        "&" => "\\&",
        "#" => "\\#",
    )
end

function format_lambda(value)
    ismissing(value) && return "NA"
    x = Float64(value)
    isnan(x) && return "NA"
    isinf(x) && return x > 0 ? "Inf" : "-Inf"
    return @sprintf("%.3f", x)
end

function lambda_lookup(rows::DataFrame)
    return Dict((Int(row.m), string(row.Grouping)) => Float64(row.Lambda) for row in eachrow(rows))
end

function write_one_table(io, rows::DataFrame, year::Int, scenario::AbstractString)
    groupings = GROUPING_ORDER[(year, string(scenario))]
    ms = sort(unique(Int.(rows.m)))
    values = lambda_lookup(rows)

    alignment = "r" * repeat("r", length(groupings))

    println(io, "\\begin{table}[!htbp]")
    println(io, "\\centering")
    println(io, "\\caption{Aggregate separation ratio \$\\Lambda\$ for $(latex_escape(year)) / $(latex_escape(scenario)).}")
    println(io, "\\begin{tabular}{$alignment}")
    println(io, "\\hline")
    println(io, join(["\$m\$"; latex_escape.(groupings)], " & "), " \\\\")
    println(io, "\\hline")

    for m in ms
        row_values = [
            haskey(values, (m, grouping)) ? format_lambda(values[(m, grouping)]) : "NA"
            for grouping in groupings
        ]
        println(io, join([string(m); row_values], " & "), " \\\\")
    end

    println(io, "\\hline")
    println(io, "\\end{tabular}")
    println(io, "\\begin{flushleft}\\footnotesize")
    println(io, "\$\\Lambda\$ is the aggregate separation ratio ")
    println(io, "\$\\Lambda = (\\sum_g \\pi_g D_g)/(\\sum_g \\pi_g W_g)\$. ")
    println(io, "Values equal to 1 indicate no excess separation; values above 1 indicate that outgroup consensuses are farther away than the ingroup consensus, relative to within-group dispersion.")
    println(io, "\\end{flushleft}")
    println(io, "\\end{table}")
    println(io)
end

function main()
    isfile(INPUT_CSV) || error("Input CSV not found at $(INPUT_CSV). Run appendix_lambda_table.jl first.")
    df = CSV.read(INPUT_CSV, DataFrame)

    open(OUTPUT_TEX, "w") do io
        println(io, "% Generated by PrefPol/running/appendix_lambda_grouping_tables.jl")
        println(io, "% Requires standard LaTeX table support only.")
        println(io)

        for spec in TARGET_SPECS
            rows = df[(df.Year .== spec.year) .& (df.Scenario .== spec.scenario), :]
            isempty(rows) && error("No rows found for $(spec.year) / $(spec.scenario).")
            write_one_table(io, rows, spec.year, spec.scenario)
        end
    end

    println("Wrote Lambda grouping LaTeX tables to $(OUTPUT_TEX)")
    return OUTPUT_TEX
end

if abspath(PROGRAM_FILE) == @__FILE__
    main()
end
